/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.bson.Document;
import test.services.database.MongoDb;

public class App {
    public static void main(String[] args) {
        // Init database connection
        try {
            init();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }

        Document[] docs = MongoDb.findAllInCollection("test");
        for (Document doc: docs) {
            System.out.println(doc.toJson());
        }
    }

    private static void init() throws Exception {
        MongoDb.init();
        System.out.println("\nConnected to database successfully\n");
    }
}
